version: '3.7'

services:
  integration:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      GRAPH_DB_ENDPOINT: graph
      GOOGLE_ACCOUNT_ID: 'YOUR GOOGLE ACCOUNT ID HERE'
      GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: '{"type": "service_account","project_id": "your-project-id","private_key_id": "your-private-key-id","private_key": "your-private-key","client_email": "your-client-email","client_id": "your-client-id","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "your-cert-url"}'
      GOOGLE_DOMAIN_ADMIN_EMAIL: 'SUBJECT USER'
    depend_on:
      - graph
  graph:
    image: tinkerpop/gremlin-server:3.3
    ports:
      - "8182:8182"
